version: "3.9"

services:
  octopie:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: octopie_dev
    image: octopie:0.0.1
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    command: bash